### ISSUE TITLE
Update the WP.org SVN repo

### ISSUE THREAD

**Issue by jrfnl** [soderlind/debug-bar-list-dependencies#14]
Hi Per,

I noticed that the SVN repo on WP.org is out of date and will probably soon start giving the 'hasn't been updated in two years' notice.

If you like, add me as a contributor in SVN and I'll update it for you (once this round of changes is done).
To add me as a contributor, visit https://wordpress.org/plugins/debug-bar-list-dependencies/admin/ and add 'jrf' under committers.

**Comment by soderlind** [comment]
done

**Comment by jrfnl** [comment]
Ok. What should we call the next version ? 1.0.7 ? 1.1 ?

**Comment by soderlind** [comment]
Let's bump the version to 1.1 :)

btw, I use grunt for deploying my other plugins (most of them) to wp.org and github. Here's an example: 
https://github.com/soderlind/css-flags/blob/master/Gruntfile.js

**Comment by soderlind** [comment]
. and, btw .. please add your name as a co-author

**Comment by jrfnl** [comment]
> Let's bump the version to 1.1 :)

My thoughts exactly ;-)

> btw, I use grunt for deploying my other plugins (most of them) to wp.org and github.

I still haven't gotten round to having a play with grunt and won't have time for that for a while. If setting this up for this repo is easy for you & you have the time, I'll leave the deploying up to you.

> please add your name as a co-author

Will do. Appreciated.

**Comment by soderlind** [comment]
I don't have time now, please commit to wp.org

**Comment by soderlind** [comment]
Juliette, I've added you as a collaborator to this project on github

**Comment by jrfnl** [comment]
For some reason people keep giving me push access... :blush:
