### ISSUE TITLE
Travis & WordPress coding standards

### ISSUE THREAD

**Issue by jrfnl** [soderlind/debug-bar-list-dependencies#7]
Would you be open to me adding a travis file which will run a PHP lint and do a code style check against the [WP Coding standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/) sniffs ?
This would include some minor changes to make the current code comply with the coding standards.

**Comment by soderlind** [comment]
Sure, please feel free to add the travis file :) I just moved from sublime text to atom and all new code is linted using wp coding standars, but old are not .. yet.

**Comment by jrfnl** [comment]
Ok, expect some PRs in the next few hours.

**Comment by soderlind** [comment]
I'll add them as they come, I'm very happy that you're doing this :)  .. and, if it takes some time before I add a PR, it just because I've hit the sack, it's late in Norway.

**Comment by jrfnl** [comment]
Great, thanks!
And yes, it's late in The Netherlands too ;-)

**Comment by soderlind** [comment]
I know ;)

**Comment by soderlind** [comment]
Btw, just remembered that WP 4.5 will have wp_add_inline_script, please see  #9

**Comment by jrfnl** [comment]
Oh - just to make sure: could you turn on the Travis service hook for this repo ?
That way as soon as the PR containing the travis config file is send in Travis will (should) start picking up on it and will test that PR to make sure it's ok ;-)

**Comment by soderlind** [comment]
I've added the travis hook

**Comment by jrfnl** [comment]
Thanks!

**Comment by soderlind** [comment]
I've enabled "Build only if .travis.yml is present"

**Comment by jrfnl** [comment]
Awesome! Putting the final touches on the PR now.

**Comment by soderlind** [comment]
@jrfnl, this travis setup you're using, where can I learn more about it ?

**Comment by jrfnl** [comment]
@soderlind From me. I've created it with some learn by trying & learn by looking at what others did ;-)

**Comment by soderlind** [comment]
I skimmed through the .travis.xml and phpcs.xml .. I thought I had to do phpunit to use Travis, my bad. As long as the test in .travis.xml, and it can be any command line test, exit with a 0, Travis gives you a :+1:  ?

**Comment by jrfnl** [comment]
> I thought I had to do phpunit to use Travis

No, but we can easily add it if someone at some point has the gusto to create some unit tests ;-)

> As long as the test in .travis.xml, and it can be any command line test, exit with a 0, Travis gives you a :+1: ?

That's the short of it, yes.

For repos which include js, I normally also include js linting & hinting against the WP standards, for instance.
For an example, see: https://github.com/jrfnl/Debug-Bar-Shortcodes/blob/master/.travis.yml
That one also includes differentiation in the linting for some PHP 5.3 code.

Also in that repo, you'll find a scrutinizer setup - just a nice way to get some pointers now and again.

**Comment by soderlind** [comment]
How do you test locally, is there a travis for localhost ?

**Comment by jrfnl** [comment]
Not that I'm aware of.

You can use git pre-commit hooks though and add relevant tasks to that.

I personally have a pre-commit hook which lints every commit through a number of PHP versions to make sure I don't commit with parse errors.

PHPCS I run manually if and when needed, but could be added to a pre-commit hook as well.

**Comment by soderlind** [comment]
Ok, I run [PHPCS in Atom](https://rezzz.com/php-codesniffer-with-wordpress-coding-standards-and-atom/), it forces me to write WPCS. It was annoying in the beginning, but I'm liking it more and more.

**Comment by jrfnl** [comment]
I've never used Atom, but that sounds interesting. And yes. forgot to mention that I have WPCS enabled in PHPStorm as well (I don't use PHPStorm that often as it's so heavy and a memory-hog).
